-- For His Glory app: database setup.
-- Run this whole file once in Supabase: Project → SQL Editor → New query → paste → Run.
-- Then run seed.sql the same way to add your songs, lyrics, Daily Bread and comments.

-- ---------- Tables ----------

create table if not exists public.songs (
  id          bigint generated by default as identity primary key,
  position    int     not null default 100,
  title_am    text    not null check (char_length(title_am) between 1 and 120),
  title_en    text    not null default '' check (char_length(title_en) <= 160),
  verse       text    not null default '' check (char_length(verse) <= 1500),
  reference   text    not null default '' check (char_length(reference) <= 120),
  youtube_id  text    not null check (youtube_id ~ '^[A-Za-z0-9_-]{6,20}$'),
  lyrics      text    not null default '' check (char_length(lyrics) <= 20000),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

create table if not exists public.bread (
  id          bigint generated by default as identity primary key,
  posted_on   date    not null default current_date,
  reference   text    not null default '' check (char_length(reference) <= 100),
  verse_text  text    not null default '' check (char_length(verse_text) <= 6000),
  reflection  text    not null default '' check (char_length(reflection) <= 6000),
  prayer      text    not null default '' check (char_length(prayer) <= 4000),
  amens       int     not null default 0 check (amens >= 0),
  created_at  timestamptz not null default now()
);

create table if not exists public.prayers (
  id          bigint generated by default as identity primary key,
  name        text    check (name is null or char_length(name) between 1 and 60),
  message     text    not null check (char_length(message) between 1 and 1000),
  prayed      int     not null default 0 check (prayed >= 0),
  hidden      boolean not null default false,
  created_at  timestamptz not null default now()
);

create table if not exists public.comments (
  id          bigint generated by default as identity primary key,
  name        text    not null default 'Anonymous' check (char_length(name) between 1 and 60),
  message     text    not null check (char_length(message) between 1 and 2000),
  hidden      boolean not null default false,
  created_at  timestamptz not null default now()
);

-- The owner (you). Add yourself after creating your login — see README.
create table if not exists public.owners (
  user_id uuid primary key references auth.users (id) on delete cascade
);

-- ---------- Who is the owner? ----------

create or replace function public.is_owner() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.owners where user_id = auth.uid());
$$;

-- ---------- Security rules ----------

alter table public.songs    enable row level security;
alter table public.bread    enable row level security;
alter table public.prayers  enable row level security;
alter table public.comments enable row level security;
alter table public.owners   enable row level security;

-- Everyone can read; only the owner sees hidden items.
drop policy if exists "read songs" on public.songs;
create policy "read songs" on public.songs for select using (is_active or public.is_owner());
drop policy if exists "read bread" on public.bread;
create policy "read bread" on public.bread for select using (true);
drop policy if exists "read prayers" on public.prayers;
create policy "read prayers" on public.prayers for select using (not hidden or public.is_owner());
drop policy if exists "read comments" on public.comments;
create policy "read comments" on public.comments for select using (not hidden or public.is_owner());
drop policy if exists "owner reads owners" on public.owners;
create policy "owner reads owners" on public.owners for select using (user_id = auth.uid());

-- Anyone can share a prayer or a comment (starts visible, with zero counts).
drop policy if exists "share prayer" on public.prayers;
create policy "share prayer" on public.prayers for insert with check (not hidden and prayed = 0);
drop policy if exists "share comment" on public.comments;
create policy "share comment" on public.comments for insert with check (not hidden);

-- Only the owner can add, edit or remove songs and Daily Bread, and hide or delete prayers/comments.
drop policy if exists "owner songs" on public.songs;
create policy "owner songs" on public.songs for all using (public.is_owner()) with check (public.is_owner());
drop policy if exists "owner bread" on public.bread;
create policy "owner bread" on public.bread for all using (public.is_owner()) with check (public.is_owner());
drop policy if exists "owner prayers update" on public.prayers;
create policy "owner prayers update" on public.prayers for update using (public.is_owner()) with check (public.is_owner());
drop policy if exists "owner prayers delete" on public.prayers;
create policy "owner prayers delete" on public.prayers for delete using (public.is_owner());
drop policy if exists "owner comments update" on public.comments;
create policy "owner comments update" on public.comments for update using (public.is_owner()) with check (public.is_owner());
drop policy if exists "owner comments delete" on public.comments;
create policy "owner comments delete" on public.comments for delete using (public.is_owner());

-- ---------- Amen and "I prayed" counters (anyone, one step at a time) ----------

create or replace function public.amen(bread_id bigint, delta int) returns int
language plpgsql security definer set search_path = public as $$
declare n int;
begin
  if delta not in (-1, 1) then raise exception 'bad delta'; end if;
  update public.bread set amens = greatest(0, amens + delta) where id = bread_id returning amens into n;
  return n;
end $$;

create or replace function public.pray_for(prayer_id bigint) returns int
language plpgsql security definer set search_path = public as $$
declare n int;
begin
  update public.prayers set prayed = prayed + 1 where id = prayer_id and not hidden returning prayed into n;
  return n;
end $$;

grant execute on function public.amen(bigint, int) to anon, authenticated;
grant execute on function public.pray_for(bigint) to anon, authenticated;
grant execute on function public.is_owner() to anon, authenticated;

-- ---------- Live updates ----------

do $$
begin
  begin alter publication supabase_realtime add table public.bread;    exception when others then null; end;
  begin alter publication supabase_realtime add table public.prayers;  exception when others then null; end;
  begin alter publication supabase_realtime add table public.comments; exception when others then null; end;
  begin alter publication supabase_realtime add table public.songs;    exception when others then null; end;
end $$;
